language: android
jdk:
    - oraclejdk8
android:
   components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - extra

    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

before_install:
    - chmod +x gradlew

script:
    - ./gradlew build check